# ===============================
# Spark Log4j2 Configuration
# ===============================

status = error
name = SparkLogConfig

# -------------------------------
# Appenders
# -------------------------------

# Rolling file appender
appender.file.type = RollingFile
appender.file.name = FileAppender
appender.file.fileName = /opt/spark/logs/spark.log
appender.file.filePattern = /opt/spark/logs/spark-%d{yyyy-MM-dd}-%i.log.gz

appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

appender.file.policies.type = Policies

# Rotate by size
appender.file.policies.size.type = SizeBasedTriggeringPolicy
appender.file.policies.size.size = 10MB

# Rotate by day
appender.file.policies.time.type = TimeBasedTriggeringPolicy
appender.file.policies.time.interval = 1

# Keep max 7 files
appender.file.strategy.type = DefaultRolloverStrategy
appender.file.strategy.max = 7


# -------------------------------
# Loggers
# -------------------------------

# Reduce Spark noise
logger.spark.name = org.apache.spark
logger.spark.level = error
logger.spark.additivity = false
logger.spark.appenderRef.file.ref = FileAppender

# Reduce Kafka noise
logger.kafka.name = org.apache.kafka
logger.kafka.level = error
logger.kafka.additivity = false
logger.kafka.appenderRef.file.ref = FileAppender

# Reduce Hadoop noise
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error
logger.hadoop.additivity = false
logger.hadoop.appenderRef.file.ref = FileAppender


# -------------------------------
# Root Logger
# -------------------------------

rootLogger.level = error
rootLogger.appenderRef.file.ref = FileAppender
